name: Bundle Analyze

on: [pull_request]

permissions:
  pull-requests: write

jobs:
  coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16.16.0

      - name: Install dependencies
        run: yarn install

      - name: Build
        run: yarn build

      # - name: Print File
      #   id: bundle-analyze
      #   run: echo "{bundle-analyze}={${{  bundle-analyze.txt}}}" >> $GITHUB_OUTPUT
      - name: Read bundle-analyze.txt
        id: bundle-analyze
        uses: juliangruber/read-file-action@v1
        with:
          path: "bundle-analyze.txt"

      - name: PR comment with reactions
        uses: thollander/actions-comment-pull-request@v2
        with:
          message: |
            <h2> :bar_chart: Bundle Analyze</h2>
            <strong>ìƒˆë¡œìš´ íŒ¨í‚¤ì§€ë¥¼ ì¶”ê°€í–ˆë‹¤ë©´ ê¼­ í™•ì¸í•´ë³´ì„¸ìš” ğŸ™„ </strong><br/>
            ë²ˆë“¤ì‚¬ì´ì¦ˆê°€ í° ìƒìœ„ 10ê°œ íŒŒì¼ì„ í™•ì¸í•´ë³¼ ìˆ˜ ìˆì–´ìš”.
            <br/>
            <br/>
            <details><summary><strong>ë¶„ì„ê²°ê³¼ ë³´ê¸°</strong></summary>

            ${{ steps.bundle-analyze.outputs.content }}

            </details>
          reactions: eyes, rocket
          comment_tag: execution
          mode: upset
